### ISSUE TITLE
My persist didnt encrypted

### ISSUE THREAD

**Issue by enricoirawan** [maxdeviant/redux-persist-transform-encrypt#64] opened 2022-05-30 04:52 UTC
![image](https://user-images.githubusercontent.com/54756728/170919207-6193612a-648f-4614-bb4d-8fd4998f3acb.png)
![image](https://user-images.githubusercontent.com/54756728/170919373-fd960d9c-459d-43a5-a771-5d4d6a120aab.png)

I tried to use this library to encrypted my persist storage, but when i run the app and check in the browser storage, the redux state didnt get encrypted, can you help me? thanks

**Comment by hichemBAALI** [comment] 2022-07-26 21:28
> ![image](https://user-images.githubusercontent.com/54756728/170919207-6193612a-648f-4614-bb4d-8fd4998f3acb.png) ![image](https://user-images.githubusercontent.com/54756728/170919373-fd960d9c-459d-43a5-a771-5d4d6a120aab.png)
> 
> I tried to use this library to encrypted my persist storage, but when i run the app and check in the browser storage, the redux state didnt get encrypted, can you help me? thanks

I think that your problem is with the key 'transforms'. You forgot to add the 's'

**Comment by jakemckenzie** [comment] 2022-07-26 23:54
I'm having the exact same issue to this, when I pull up the redux states with the app running in the browser after using this library all the states are visible. Not sure what's happening with this library but it does not appear to be encrypting any data.

**Comment by maxdeviant** [comment] 2022-07-29 02:07
Could you provide an example repo with a minimal reproduction case?

**Comment by jakemckenzie** [comment] 2022-07-29 07:48
@maxdeviant before I produce you a reproduction because my project is closed source: is this module only meant to encrpyt the states while the application is not running and the states are stored in local storage?

**Comment by maxdeviant** [comment] 2022-07-29 12:59
> @maxdeviant before I produce you a reproduction because my project is closed source: is this module only meant to encrypt the states while the application is not running and the states are stored in local storage?

Yes, the state is only encrypted at rest. When the store is hydrated from the persisted copy the in-memory state will be decrypted.

**Comment by jakemckenzie** [comment] 2022-08-02 14:45
> ction because my project is closed source: is this module only meant to encrypt the states while the application is not running

Alright well on my end this was a miscommunication and I suspect the original poster as well. I expected the state to be encrypted regardless of whether the app was running or not.

**Comment by maxdeviant** [comment] 2023-03-25 02:55
Closing because no repro was provided.

**Closed by maxdeviant** 2023-03-25 02:55 UTC
Labels: needs repro
