### ISSUE TITLE
Issues using with redux-persist and AsyncStorage

### ISSUE THREAD

**Issue by austin-sprawls** [maxdeviant/redux-persist-transform-encrypt#15] opened 2017-04-05 20:05 UTC
I'm using redux-persist and AsyncStorage to persist my redux state, but I'm running into issues using this library with them. I've attempted using both the sync and async libs, but both give me errors:

![img_0047](https://cloud.githubusercontent.com/assets/22301287/24724596/84519352-1a00-11e7-8680-187c7955b9a8.PNG)

![img_0048](https://cloud.githubusercontent.com/assets/22301287/24724598/8738877e-1a00-11e7-81db-d35a8dd1aad4.PNG)

**Comment by maxdeviant** [comment] 2017-04-05 22:29
@austin-sprawls This looks like the same problem as in #13.

I see you posted two screenshots. Is the first one using the sync methods and the second one using the async methods?

**Comment by maxdeviant** [comment] 2017-04-05 22:35
@austin-sprawls The second screenshot's error message looks the same as the one in #10. I think the async implementation is not currently compatible with React Native (async support in general is still WIP).

**Comment by austin-sprawls** [comment] 2017-04-05 22:41
Right, the second screenshot is the async method.

**Comment by austin-sprawls** [comment] 2017-04-05 22:48
I tried replacing the json-stringify-safe call with JSON.stringify in the helper file, but it still errors "encrypt: expected outbound state to  be  a string"

**Comment by maxdeviant** [comment] 2017-04-06 00:53
@austin-sprawls I haven't worked with React Native before, but I will see if I can put together a repro using [create-react-native-app](https://github.com/react-community/create-react-native-app).

**Comment by maxdeviant** [comment] 2017-04-06 01:48
I added an [example React Native](https://github.com/maxdeviant/redux-persist-transform-encrypt/tree/master/examples/ReactNativeExample) to help me reproduce the issue.

I'm running into this error though:

![screen shot 2017-04-05 at 9 45 22 pm](https://cloud.githubusercontent.com/assets/1486634/24734029/42b35504-1a49-11e7-9d63-51be4f95faef.png)

@austin-sprawls Would you mind taking a look and seeing if you can help me reproduce your issue in the repo?

**Comment by maxdeviant** [comment] 2017-04-06 02:36
@austin-sprawls Okay, I got the example working, but I am not getting the same error.

Are you using any other `redux-persist` transforms?

**Comment by askiiRobotics** [comment] 2017-04-06 17:00
Hi all,

It seems that makeAsyncDecryptor won't unpack values. So autoRehydrate throws promise in makeDecryptor. Very strange.

**Comment by maxdeviant** [comment] 2017-04-06 17:24
@askiiRobotics The async decrypt implementation is not working. But I think the sync methods should still work with ReactNative's AsyncStorage.

**Comment by joshuajung** [comment] 2017-05-06 16:29
I'm seeing the same error message ("expected outbound state to be a string") using the sync implementation, using no other transforms and a very simple store. @austin-sprawls, did you make any progress?

**Comment by momosh** [comment] 2017-05-24 23:19
I'm getting the same error here ("redux-persist-transform-encrypt: expected outbound state to be a string"), while using the sync implementation and I'm using the library version 1.0.2

**Comment by maxdeviant** [comment] 2017-05-25 16:04
@joshuajung @momosh Are both of you on React Native as well? I have not been able to reproduce this issue in React Native. You can refer to the [example](https://github.com/maxdeviant/redux-persist-transform-encrypt/tree/master/examples/ReactNativeExample) project to see if there are any differences.

A repo with a repro case in it would be most helpful.

**Comment by thiagofernando** [comment] 2017-05-29 12:39
I had the same issue.
I created a test repository for you.

 https://github.com/thiagofernando/Persist

**Comment by maxdeviant** [comment] 2017-05-29 15:46
@thiagofernando Thanks! I'll have a look at it.

**Comment by momosh** [comment] 2017-05-29 16:27
@thiagofernando yes, got this error while working with React Native. Also checked the example you linked, but could not make it work with redux-persist-immutable.
But, I've switched to redux-persist and everything works as expected.

**Comment by thiagofernando** [comment] 2017-05-29 23:38
Turn on the debug you can see better, in this new version of the react is not appearing the red screen, but the data is not storing.
Save a card, then reload. it will not be there.

**Comment by fdobre** [comment] 2017-07-15 15:45
I get the same error using react-native 0.45.1 and redux-persist-transform-encrypt 1.0.2 (the sync version):
`expected outbound state to be a string`
Did anyone find a solution for this?

**Comment by maxdeviant** [comment] 2017-07-15 15:49
@fdobre I've been meaning to look into this issue, but haven't had the time to do so.

Are you using any other transforms? Or just `redux-persist-transform-encrypt`?

**Comment by fdobre** [comment] 2017-07-15 16:43
No, I'm not using any other transforms:
`const encryptor = createEncryptor({
  secretKey: 'my-super-secret-key-999',
});


persistStore(
  store,
  {
    storage: AsyncStorage,
    whitelist: ['auth'],
    transforms: [encryptor],
  },
);`

and in auth state is something like this:

```
{
  user: {
     uid: 'kK6HGrd3nOMltYE6ltbocUp4WoU2',
     email: 'test@test.com'
  },
  token: '',
}
```

**Comment by yogeshwar-20** [comment] 2017-07-18 04:53
It seems like this is caused when you're trying to apply transform-encrypt onto a previously persisted un-encrypted store? I was running into this same issue until I purged the store and started afresh with encrypt on and it seems to be behaving right now. Could that be it?

**Comment by fdobre** [comment] 2017-07-18 07:51
Tried purge several times. It doesn't work on my side.

**Comment by hectorsabina** [comment] 2017-08-14 18:14
Had same issue described here (also for a RN project, not using any other transforms), purging the store also worked for me. Not sure if that's indeed the issue (as @yogeshwar-20 suggested) but try this out:

First remove the transform from the config and purge:
`persistStore(store, { storage: AsyncStorage }).purge()`

And then, add the transform back again and don't purge:
`persistStore(store, { storage: AsyncStorage, transforms: [ encryptor ] })`

**Comment by jbrodriguez** [comment] 2018-03-14 12:47
An alternative solution, to prevent losing the stored state, would be

```javascript
const version = 1

const migrations = {
	0: state => state, // the migration actually takes place in the transformer below
}

const encryptor = createEncryptor({
	secretKey: 'secret',
})

const transformer = createTransform(
	(inboundState, key) => {
		return inboundState
	},
	(outboundState, key, fullState) => {
		if (fullState._persist.version === 0) {
			return AES.encrypt(outboundState, 'secret').toString()
		}

		return outboundState
	},
	{},
)

const config = {
	...
	storage: AsyncStorage,
	version,
	migrate: createMigrate(migrations),
	transforms: [encryptor, transformer],
}

const reducer = persistReducer(config, rootReducer)
```

Here I assume that version 0 is unencrypted and I'm migrating to version 1 which is encrypted.

So, if the stored state is at version 0, the transformer encrypts it (with the same logic used by the plugin) and offers it to the next transform, which is the encryptor (decryptor in this case).

This would be more elegant if **migrate** ran before **transforms**, but that's not the case right now.

**Comment by maxdeviant** [comment] 2020-10-17 15:11
Closing due to age.

**Closed by maxdeviant** 2020-10-17 15:11 UTC
Labels: bug
